### PR TITLE
Updating the readme to include instructions on how to use the library

### PR DESCRIPTION
**Pull request by f4ngy**
I've added instructions to the readme so that people outside of HFOSS at RIT will know how to use the library!

### CODE REVIEW

**Comment by f4ngy** [comment]
Got it, I'll make those changes over the weekend and let you know when they're done!

**Comment by f4ngy** [comment]
@DAWacker I made the changes you requested!

**Comment by DAWacker** [comment]
@lle6138 This is good, except after you pip install sugar_badges, the user is now able to use this import statement:

> from sugar_badges import badges
> self.badges = badges(activity_name, activity_bundle_id)

Badges are also awarded in this manner:

> self.badges.award(badge_name, badge_description)

Make these changes and this will be ready to merge.

**Comment by f4ngy** [comment]
Er, I have this in the readme, I copied the format from SkyTime:

+To use the badge library in your existing project you will need to add this line to the top of your Python file:

+from badges import badges

+To enable badges in your game, add this line to your init:

+self.badges = badges("Activity Name Here", bundle_id)

But I should make it match what you wrote exactly?

**Comment by DAWacker** [comment]
No, what is on the README for SkyTime is before we had sugar_badges able to be pip installed, you should use what I said in my previous comment.

**Comment by f4ngy** [comment]
Okay, thank you for explaining  @DAWacker .  I made the changes.

**Comment by f4ngy** [comment]
@DAWacker status update?

**Comment by DAWacker** [comment]
:+1:

**Pull request merged**
